### ISSUE TITLE
Single Page Everything: Endless redirect

### ISSUE THREAD

**Issue by debdrup** [leesei/userscripts#1]
Hiya!

As of a few days ago, I noticed that Ars would just get stuck in a loop trying to constantly redirect - but at the time I couldn't figure out why.

However, I just realized today that it might be this userscript, so after disabling it and confirming that Ars loads, then subsequently enabling it again to confirm that the redirect happens, I can't conclude anything other than it's this userscript doing it.

Do you think it's something that can be fixed?

**Comment by leesei** [comment]
I tried Ars and it seems okay.
Do you have the specific URL that causes the loop?

**Comment by leesei** [comment]
I ravamped the implementation and the looping issue (on top level topic page) is fixed.
Please update.
